spring.application.name=medvault-backend

# Server Port
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:medvault;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (Move to env vars in production)
jwt.secret=94a08da1fecbb6e8b46990538c7b50b298402157a4128f9d510619bc0195e347
jwt.expiration=86400000
